# -*- coding: utf-8 -*-
"""重启工作站边车 v3。

启动通道结论：
  - Popen(wscript/node, DETACHED)：命令一结束就被回收 ✗
  - ShellExecuteW open/runas：同样被回收 ✗
  - 计划任务：被程序黑名单硬拦 ✗
  - wt.exe（App Execution Alias 激活，脱离作业对象）：命令**正常结束**时存活 ✓
    （但外层命令若超时被 SIGTERM，整树连坐 —— 调用方务必给足 timeout）

流程：
  1. 杀掉监听 5278 的旧进程
  2. 脚本本体 scripts/Workstation.vbs 缺失（或里面的 node 已经不是现在这个）就生成一份
     （这个文件**不进版本库**，是运行时产物；GBK/UTF-16 都能被 wscript 读，这里写 UTF-16LE+BOM）
  3. 在启动文件夹建/修 Workstation.lnk（指向 wscript + 那个 vbs），并清掉历史命名的旧自启项
  4. wt.exe 独立窗口起新边车，轮询 /api/health 就绪（探测禁代理，防 502 误判）

为什么是 .lnk 而不是直接把 .vbs 放进启动文件夹（Windows 上适用，Linux / macOS 不适用）：
  Windows 的策略会拦计划任务，且禁止在启动文件夹新建 .vbs / .cmd —— open、Copy-Item、改名全报「拒绝访问」，
  只有 .txt 与 .lnk 放行；覆盖一个已存在的 .vbs 反而是允许的，所以老写法是
  「看着一直能用，一旦那条 vbs 被删就再也装不回去」。详见 server/lib/autostart.mjs。
"""
import os
import shutil
import subprocess
import tempfile
import time
import urllib.request


# --------------------------------------------------------------- 路径解析 ---
# 下面这几项**都不写死本机路径**：
#   · 项目根      = 本文件的上两级目录（scripts/ 的父目录）
#   · node        = 先看 WS_NODE 环境变量，再 PATH（shutil.which("node")），
#                   最后才是常见安装位
#   · 启动文件夹  = %APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup
#   · Windows Terminal = shutil.which("wt")；取不到就不用它
#     （「无窗口」本来就是期望行为，所以没有 wt 反而更省事）
# 写死的 node 绝对路径对别人必然失效（随安装方式而变），所以只按上面三级找。
def _find_node():
    env = os.environ.get("WS_NODE")
    if env and os.path.exists(env):
        return env
    found = shutil.which("node")
    if found:
        return found
    for cand in (
        os.path.join(os.environ.get("ProgramFiles", r"C:\Program Files"), "nodejs", "node.exe"),
        os.path.join(os.environ.get("LOCALAPPDATA", ""), "Programs", "nodejs", "node.exe"),
    ):
        if cand and os.path.exists(cand):
            return cand
    return "node"


def _startup_dir():
    return os.path.join(
        os.environ.get("APPDATA", os.path.expanduser("~")),
        "Microsoft", "Windows", "Start Menu", "Programs", "Startup",
    )


def _wt():
    return shutil.which("wt") or ""


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NODE = _find_node()
PORT = int(os.environ.get("WS_PORT") or 5278)
OUT = os.path.join(ROOT, "logs", "restart-sidecar.txt")
# 自启项名 = 用户在「任务管理器 → 启动应用」里看到的名字
LNK_NAME = "Workstation.lnk"
VBS_NAME = "Workstation.vbs"
# 改过名的旧自启项：留着会让开机起两个边车，得随安装一起清掉。这里默认留空 ——
# 老名字本身就是某台机器上的痕迹，不再写进仓库。如果你以前装过、任务管理器「启动应用」里
# 还能看到旧条目，手工到启动文件夹里删掉那一条就行。
LEGACY_NAMES = []
STARTUP = _startup_dir()

VBS_CONTENT = (
    "' Workstation（工作站边车）静默自启 —— generated by restart-sidecar.py\n"
    "Dim shell\n"
    "Set shell = CreateObject(\"WScript.Shell\")\n"
    f"shell.CurrentDirectory = \"{ROOT}\"\n"
    f"shell.Run \"\"\"{NODE}\"\" \"\"{ROOT}\\server\\index.mjs\"\"\", 0, False\n"
)

lines = []


def log(msg):
    lines.append(str(msg))


# 探测必须禁代理：环境里若有 HTTP_PROXY，会把 127.0.0.1 请求送到代理，
# 返回 502 Bad Gateway，看起来像「进程坏了」，实际是假象。
OPENER = urllib.request.build_opener(urllib.request.ProxyHandler({}))


def probe(timeout=3):
    try:
        req = urllib.request.Request(
            f"http://127.0.0.1:{PORT}/api/health", headers={"Accept": "application/json"}
        )
        with OPENER.open(req, timeout=timeout) as r:
            return r.status, r.read(200)
    except Exception as e:  # noqa: BLE001
        return None, f"{type(e).__name__}: {e}"


# 1. 杀旧实例（netstat 输出是 GBK，按字节拿再解码）
pids = set()
try:
    raw = subprocess.run(["netstat", "-ano", "-p", "TCP"], capture_output=True, timeout=15).stdout
    text = raw.decode("gbk", errors="replace")
    for line in text.splitlines():
        parts = line.split()
        if len(parts) >= 5 and parts[1].endswith(f":{PORT}") and parts[3] == "LISTENING":
            pids.add(parts[4])
except Exception as e:  # noqa: BLE001
    log(f"netstat failed: {e}")

log(f"listening pids: {sorted(pids)}")
for pid in sorted(pids):
    try:
        k = subprocess.run(["taskkill", "/F", "/PID", pid], capture_output=True, timeout=10)
        log(f"taskkill {pid}: rc={k.returncode} {k.stdout.decode('gbk', 'replace').strip()[:100]}")
    except Exception as e:  # noqa: BLE001
        log(f"taskkill {pid} failed: {e}")

released = False
for _ in range(12):
    st, _ = probe()
    if st is None:
        released = True
        break
    time.sleep(1)
log("port released" if released else "port STILL BUSY after 12s!")

# 2. 脚本本体：只在「还没有」或「里面的 node 已经不是现在这个」时重写。
#    面板的「重建」会生成带日志重定向的版本，没必要用这个简版覆盖掉它。
vbs_local = os.path.join(ROOT, "scripts", VBS_NAME)
cur = ""
if os.path.exists(vbs_local):
    raw = open(vbs_local, "rb").read()
    try:
        cur = raw.decode("utf-16" if raw[:2] == b"\xff\xfe" else "gbk", errors="replace")
    except Exception:
        cur = ""
if NODE.replace("/", "\\") in cur.replace("/", "\\") and cur:
    log(f"vbs kept (already points at {NODE}): {vbs_local}")
else:
    with open(vbs_local, "w", encoding="utf-16") as f:  # utf-16 = UTF-16LE + BOM，wscript 最认这个
        f.write(VBS_CONTENT)
    log(f"vbs written: {vbs_local}")

# 3. 开机自启位 = 启动文件夹里的一条 .lnk（本机策略禁止在那儿新建 .vbs/.cmd，只放行 .lnk）。
#    PowerShell 脚本必须先落成 UTF-8+BOM 的 .ps1 再 -File 执行：中文路径走命令行会被代码页糟蹋。
lnk = os.path.join(STARTUP, LNK_NAME)
ps_script = (
    '$ErrorActionPreference = "Stop"\r\n'
    '$ws = New-Object -ComObject WScript.Shell\r\n'
    f'$s = $ws.CreateShortcut("{lnk}")\r\n'
    '$s.TargetPath = "$env:SystemRoot\\System32\\wscript.exe"\r\n'
    f"$s.Arguments = '\"{vbs_local}\"'\r\n"
    f'$s.WorkingDirectory = "{ROOT}"\r\n'
    "$s.WindowStyle = 7\r\n"
    '$s.Description = "Workstation"\r\n'
    "$s.Save()\r\n"
)
ps_file = os.path.join(tempfile.gettempdir(), f"ws-make-lnk-{os.getpid()}.ps1")
try:
    with open(ps_file, "w", encoding="utf-8-sig") as f:
        f.write(ps_script)
    r = subprocess.run(
        ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", ps_file],
        capture_output=True,
        timeout=30,
    )
    err = (r.stderr or b"").decode("gbk", "replace").strip()[:200]
    if os.path.exists(lnk):
        log(f"autostart installed: {lnk}")
    else:
        log(f"autostart install FAILED (rc={r.returncode}) {err}")
    os.remove(ps_file)
except Exception as e:  # noqa: BLE001
    log(f"autostart install failed: {e}")

# 3b. 清掉改名前留下的旧自启项（含被关掉时改成的 .disabled 变体）。
#     不清的话，开机时新旧两条都会跑，第二个实例撞 5278 后自己退出，看着像随机故障。
for legacy in LEGACY_NAMES:
    for place in (STARTUP, os.path.join(ROOT, "scripts")):
        for suffix in ("", ".disabled"):
            p = os.path.join(place, legacy + suffix)
            try:
                if os.path.exists(p):
                    os.remove(p)
                    log(f"removed legacy autostart: {p}")
            except Exception as e:  # noqa: BLE001
                log(f"remove legacy {p} failed: {e}")

# 4. 启动：**默认无窗口**。
#
# 为什么不再首选 wt.exe：wt 每次都会开一个可见终端窗口，而「脱离父进程所在的作业对象」
# 这件事靠 CREATE_BREAKAWAY_FROM_JOB 一样能做到 —— 结果是任务栏会攒出一排
# node.exe 的可见终端窗口。
# 现在顺序：无窗口游离进程（隐藏 + 断作业对象 + 输出落 logs/sidecar.log）→ wt（可见，最后手段）。
WT = _wt()  # 取不到就不用它（无窗口是期望行为）
CREATE_NO_WINDOW = 0x08000000
CREATE_BREAKAWAY_FROM_JOB = 0x01000000
clean_env = dict(os.environ)
for _k in ("HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "http_proxy", "https_proxy", "all_proxy"):
    clean_env.pop(_k, None)
clean_env["NO_PROXY"] = "*"
log_path = os.path.join(ROOT, "logs", "sidecar.log")
entry = os.path.join(ROOT, "server", "index.mjs")
header = "\n===== %s 启动（无窗口） =====\n" % time.strftime("%Y-%m-%d %H:%M:%S")

started = False
try:
    with open(log_path, "ab") as lf:
        lf.write(header.encode("utf-8"))
        subprocess.Popen(
            [NODE, entry],
            cwd=ROOT,
            env=clean_env,
            stdout=lf,
            stderr=subprocess.STDOUT,
            creationflags=subprocess.DETACHED_PROCESS
            | subprocess.CREATE_NEW_PROCESS_GROUP
            | CREATE_NO_WINDOW
            | CREATE_BREAKAWAY_FROM_JOB,
        )
    log("hidden launched (no window), log=%s" % log_path)
    started = True
except Exception as e:  # noqa: BLE001
    log("hidden launch failed: %s" % e)
    try:
        with open(log_path, "ab") as lf:
            subprocess.Popen(
                [NODE, entry],
                cwd=ROOT,
                env=clean_env,
                stdout=lf,
                stderr=subprocess.STDOUT,
                creationflags=subprocess.DETACHED_PROCESS | subprocess.CREATE_NEW_PROCESS_GROUP | CREATE_NO_WINDOW,
            )
        log("hidden launched (no breakaway)")
        started = True
    except Exception as e2:  # noqa: BLE001
        log("hidden launch retry failed: %s" % e2)

if not started:
    try:
        subprocess.Popen(
            [WT, "-d", ROOT, NODE, entry],
            creationflags=subprocess.DETACHED_PROCESS | subprocess.CREATE_NEW_PROCESS_GROUP,
            env=clean_env,
        )
        log("wt launched (可见窗口，最后手段)")
    except Exception as e:  # noqa: BLE001
        log("wt launch failed: %s" % e)


def wait_ready(seconds):
    last = (None, "")
    for _ in range(seconds):
        time.sleep(1)
        last = probe()
        if last[0] == 200:
            return True, last
    return False, last


ok, (st, body) = wait_ready(12)
if not ok:
    try:
        with open(log_path, "ab") as lf:
            subprocess.Popen(
                [NODE, os.path.join(ROOT, "server", "index.mjs")],
                cwd=ROOT,
                env=clean_env,
                stdout=lf,
                stderr=subprocess.STDOUT,
                creationflags=subprocess.DETACHED_PROCESS | subprocess.CREATE_NEW_PROCESS_GROUP | CREATE_NO_WINDOW,
            )
        log(f"node fallback launched (no window), log={log_path}")
    except Exception as e:  # noqa: BLE001
        log(f"node fallback failed: {e}")
    ok, (st, body) = wait_ready(20)

if ok:
    log(f"READY: {body[:160]!r}")
else:
    log(f"NOT READY, last probe: {st} {body}")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("\n".join(lines))
